# Generated by Django 4.0.3 on 2022-03-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feild_img',
            field=models.ImageField(blank=True, upload_to='featured_img'),
        ),
    ]
